modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/chronosacaria/MCStoryModeArmors/issues"
license = "MIT"

[[mods]]
modId = "mcsa"
version = "${version}"
displayName = "MC Story Mode Armor"
authors = "chronosacaria"
description = '''
Brings the armours from Minecraft Story Mode to Minecraft Java
'''
#logoFile = ""

[[dependencies.mcsa]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mcsa]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mcsa]]
modId = "architectury"
mandatory = true
versionRange = "[4.6.77,)"
ordering = "AFTER"
side = "BOTH"